
SET LOG_FILE="SCRIPTS.LOG"
SET SERVICE_1C_NAME="1C:Enterprise 8.3 Server Agent (x86-64)"
SET SERVICE_1C_NAME2="1C:Enterprise 8.3 Server Agent 2540 8.3.15"
SET SERVICE_1C_NAME3="1C:Enterprise 8.3 Configuration Repository Server 8.3.15"
SET SERVICE_1C_NAME4="1C:Enterprise 8.3 Configuration Repository Server"
:: SET SERVICE_RAS_NAME="1C:ENTERPRISE 8.3 REMOTE SERVER"
SET CNTX_PATH="c:\Program Files\1cv8\srvinfo\reg_1541"
SET CNTX_PATH2="C:\Program Files\1cv8\srvinfo2541\reg_2541"
SET PFL_PATH="C:\PROGRAMDATA\1C\1CV8"
SET TEMP_PATH="%TEMP%"
SET TEMP_PATH2="C:\Users\1cservice\AppData\Local\Temp"
SET TEMP_PATH3="C:\Windows\Temp"

ECHO %DATE% %TIME% STOP SERVICE %SERVICE_1C_NAME% >> "%~DP0"%LOG_FILE%

SC STOP %SERVICE_1C_NAME%
SC STOP %SERVICE_1C_NAME2%
SC STOP %SERVICE_1C_NAME3%
SC STOP %SERVICE_1C_NAME4%
:: SC STOP %SERVICE_RAS_NAME%


TIMEOUT 20

TASKKILL /F /IM "RPHOST.EXE"
TASKKILL /F /IM "RMNGR.EXE"
TASKKILL /F /IM "RAGENT.EXE"
TASKKILL /F /IM "RAS.EXE"

TIMEOUT 15

ECHO %DATE% %TIME% DONE STOP SERVICE %SERVICE_1C_NAME% >> "%~DP0"%LOG_FILE%

ECHO %DATE% %TIME% START CLEAN TEMP >> "%~DP0"%LOG_FILE%

DEL /Q /F /S %CNTX_PATH%\SNCCNTX*
DEL /Q /F /S %CNTX_PATH2%\SNCCNTX*

DEL /Q /F %PFL_PATH%\*.PFL
DEL /Q /F /S %TEMP_PATH%\*.*
DEL /Q /F /S %TEMP_PATH2%\*.*
DEL /Q /F /S %TEMP_PATH3%\*.*

ECHO %DATE% %TIME% DONE CLEAN TEMP >> "%~DP0"%LOG_FILE%

TIMEOUT 15

ECHO %DATE% %TIME% START SERVICE %SERVICE_1C_NAME% >> "%~DP0"%LOG_FILE%

SC START %SERVICE_1C_NAME%
SC START %SERVICE_1C_NAME2%
SC START %SERVICE_1C_NAME3%
SC START %SERVICE_1C_NAME4%
:: SC START %SERVICE_ RAS _NAME%

ECHO %DATE% %TIME% SERVICE %SERVICE_1C_NAME% RESTARTED >> "%~DP0"%LOG_FILE%
